baseURL       = "/about/"

languageCode  = "en-us"
title         = "Roxo | Creative Design Agency"
theme = "roxo-hugo"
summarylength = 25

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Mission and Vision"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Outreach"
    url     = "outreach"
    weight  = 4
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5
  [[menu.nav]]
    name    = "Onua 3tis3n"
    url     = "3tis3n"
    weight  = 6

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/FORM_ID"
  method = "POST"

  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Your Mind Dey!"
    tagline               = "Normalizing mental health discourse amongst senior high school students in Ghana"
    primary_button        = "What We Can Achieve Together"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "THE CHOP BOX ROOM"
    subtitle  = "Opening the mental padlock that prevents us from engaging with our emotions"
    primary_button = "Maintaining healthy emotional wellbeing:COVID Edition"
    primary_button_url = "3tis3n"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S BEGIN THE CONVERSATIONS!"
    primary_button      = "Interested in Joining Us?"
    primary_button_url  = "contact"
    #secondary_button    = "Not Convinced"
    #secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      #address = "713 Elmwood St.<br>Prior Lake, MN 55372"
      phone   = "+1 651 434 7672"
      email   = "mentalhealthghana@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "Who We Are"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Outreach"
          url  = "outreach"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "https://www.facebook.com/YMDgh"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/your_mind_dey/"
        [[params.footer.social.link]]
          name = "Whatsapp"
          url  = "#"
        [[params.footer.social.link]]
          name = "YouTube"
          url  = "#"

